module.exports=[
    {
        srNo:1,
        name:'stoners',
        country:'Tunisia',
        city:'Tunis',
        phone:'00000000',
        email:'contact@stoners.tn'
    },
    {
        srNo:1,
        name:'stoners',
        country:'Tunisia',
        city:'Tunis',
        phone:'00000000',
        email:'contact@stoners.tn'
    },
    {
        srNo:1,
        name:'stoners',
        country:'Tunisia',
        city:'Tunis',
        phone:'00000000',
        email:'contact@stoners.tn'
    },
    {
        srNo:1,
        name:'stoners',
        country:'Tunisia',
        city:'Tunis',
        phone:'00000000',
        email:'contact@stoners.tn'
    },
    {
        srNo:1,
        name:'stoners',
        country:'Tunisia',
        city:'Tunis',
        phone:'00000000',
        email:'contact@stoners.tn'
    },
    {
        srNo:1,
        name:'stoners',
        country:'Tunisia',
        city:'Tunis',
        phone:'00000000',
        email:'contact@stoners.tn'
    },
    {
        srNo:1,
        name:'stoners',
        country:'Tunisia',
        city:'Tunis',
        phone:'00000000',
        email:'contact@stoners.tn'
    },
    {
        srNo:1,
        name:'stoners',
        country:'Tunisia',
        city:'Tunis',
        phone:'00000000',
        email:'contact@stoners.tn'
    },
    {
        srNo:1,
        name:'stoners',
        country:'Tunisia',
        city:'Tunis',
        phone:'00000000',
        email:'contact@stoners.tn'
    },
    {
        srNo:1,
        name:'stoners',
        country:'Tunisia',
        city:'Tunis',
        phone:'00000000',
        email:'contact@stoners.tn'
    },
]